// QuantWeave Frontend v3.0
const API=localStorage.getItem('qw_api')||'http://localhost:8000';
const T={dashboard:'交易仪表盘',screening:'智能选股',signals:'每日信号',strategy:'策略管理',backtest:'回测中心',market:'市场行情',risk:'风控中心',settings:'系统设置'};
const I=['📊','🔍','📡','⚡','🔬','📈','🛡️','⚙️'];
const PK=['dashboard','screening','signals','strategy','backtest','market','risk','settings'];
let CP='',ST=[];
const $=id=>document.getElementById(id);

document.addEventListener('DOMContentLoaded',()=>{loadST();nav('dashboard');setInterval(()=>{const t=$('ht');if(t)t.textContent=new Date().toLocaleString('zh-CN',{hour12:false})},1000)});
async function api(p,o){try{const r=await fetch(API+'/api/v1'+p,{headers:{'Content-Type':'application/json'},...o});if(!r.ok)throw r.status;return await r.json()}catch(e){return null}}
async function loadST(){const r=await api('/strategies/types');ST=r?.items||[{key:'dual_ma',name:'双均线交叉'},{key:'bollinger',name:'布林带突破'},{key:'rsi',name:'RSI超买超卖'},{key:'macd',name:'MACD金叉死叉'}]}
function toast(m,t){const e=document.createElement('div');e.style.cssText='position:fixed;top:20px;right:20px;z-index:9999;padding:12px 20px;border-radius:10px;background:#fff;box-shadow:0 10px 15px rgba(0,0,0,.1);font-size:13px;border-left:4px solid '+(t==='error'?'#ef4444':'#10b981');e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3000)}
function showToast(m,t){toast(m,t)}

function nav(p){
  CP=p;
  $('app').innerHTML=`<div style="display:flex;height:100vh;font-family:'Plus Jakarta Sans',system-ui,sans-serif">
    <aside style="width:230px;background:#fff;border-right:1px solid #e2e8f0;display:flex;flex-direction:column;flex-shrink:0">
      <div style="height:56px;display:flex;align-items:center;padding:0 16px;border-bottom:1px solid #f1f5f9;gap:10px">
        <div style="width:30px;height:30px;background:linear-gradient(135deg,#10b981,#06b6d4);border-radius:6px;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:13px">Q</div>
        <h1 style="font-size:15px;font-weight:700;background:linear-gradient(135deg,#10b981,#06b6d4);-webkit-background-clip:text;-webkit-text-fill-color:transparent">QuantWeave</h1>
      </div>
      <nav style="padding:10px 8px;flex:1">${PK.map((k,i)=>`${i===0||i===3?`<div style="font-size:10px;font-weight:600;color:#94a3b8;padding:8px 12px 4px">${i===0?'交易':'监控'}</div>`:''}<div onclick="nav('${k}')" style="display:flex;align-items:center;gap:10px;padding:8px 12px;border-radius:6px;cursor:pointer;font-size:13px;font-weight:${k===p?'600':'500'};color:${k===p?'#10b981':'#475569'};background:${k===p?'#ecfdf5':'transparent'};margin-bottom:2px">${I[i]} ${T[k]}</div>`).join('')}</nav>
      <div style="padding:10px 14px;border-top:1px solid #f1f5f9;font-size:10px;color:#94a3b8">v1.0.0</div>
    </aside>
    <main style="flex:1;display:flex;flex-direction:column;overflow:hidden">
      <header style="height:56px;background:#fff;border-bottom:1px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between;padding:0 24px;flex-shrink:0">
        <h2 style="font-size:17px;font-weight:700">${T[p]}</h2>
        <div style="display:flex;gap:10px;align-items:center"><span id="ht" style="font-family:'JetBrains Mono',monospace;font-size:11px;color:#94a3b8"></span><button onclick="nav(CP)" style="padding:4px 10px;border-radius:6px;font-size:11px;cursor:pointer;border:1px solid #e2e8f0;color:#475569;background:transparent">🔄</button></div>
      </header>
      <div id="bc" style="flex:1;overflow-y:auto;padding:24px;background:#f8fafb"></div>
    </main></div>`;
  setTimeout(()=>window['r_'+p]&&window['r_'+p](),0);
}

// ---- DASHBOARD ----
function r_dashboard(){
  $('bc').innerHTML=`<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px">${['总资产|¥1,000,000','今日收益|¥0','运行策略|0','风控告警|0'].map(s=>{const[l,v]=s.split('|');return`<div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:16px 18px"><div style="font-size:11px;color:#94a3b8;margin-bottom:4px">${l}</div><div style="font-size:22px;font-weight:700;font-family:'JetBrains Mono',monospace">${v}</div></div>`}).join('')}</div><div style="display:grid;grid-template-columns:2fr 1fr;gap:16px"><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">📈 收益曲线</div><div style="padding:18px"><canvas id="eqC" height="240"></canvas></div></div><div><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;margin-bottom:14px"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">⚡ 策略</div><div id="ds" style="padding:12px;font-size:12px;color:#94a3b8">加载中...</div></div><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">🔔 告警</div><div style="padding:12px;font-size:12px;color:#94a3b8">暂无</div></div></div></div>`;
  (async()=>{const r=await api('/strategies');const e=$('ds');if(e){if(r?.items?.length)e.innerHTML=r.items.slice(0,5).map(s=>`<div style="padding:6px 0;display:flex;justify-content:space-between"><span>${s.name}</span><span style="color:${s.status==='running'?'#10b981':'#94a3b8'}">${s.status}</span></div>`).join('');else e.textContent='暂无策略'}const ctx=$('eqC');if(ctx){const d=Array.from({length:60},(_,i)=>1000000+Math.sin(i/10)*20000+i*500);new Chart(ctx,{type:'line',data:{labels:d.map((_,i)=>i),datasets:[{data:d,borderColor:'#10b981',backgroundColor:'rgba(16,185,129,.1)',fill:true,tension:.4,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{display:false},y:{ticks:{callback:v=>'¥'+(v/10000).toFixed(0)+'万'}}}}})}})();
}

// ---- SCREENING ----
function r_screening(){
  // Create temp mainContent for renderScreening() to write into
  let temp = document.createElement('div');
  temp.id = 'mainContent';
  temp.style.cssText = 'position:absolute;left:-9999px';
  document.body.appendChild(temp);
  renderScreening();
  const bc = $('bc');
  if(bc && temp.innerHTML){
    bc.innerHTML = temp.innerHTML;
  }
  temp.remove();
}

// ---- SIGNALS ----
function r_signals(){
  let temp = document.createElement('div');
  temp.id = 'mainContent';
  temp.style.cssText = 'position:absolute;left:-9999px';
  document.body.appendChild(temp);
  renderSignals();
  const bc = $('bc');
  if(bc && temp.innerHTML){
    bc.innerHTML = temp.innerHTML;
  }
  temp.remove();
}

// ---- STRATEGY ----
function r_strategy(){
  $('bc').innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><h3 style="font-size:15px;font-weight:700">策略列表</h3><button onclick="showCS()" style="padding:7px 14px;border-radius:6px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:#10b981;color:#fff">+ 新建</button></div><div id="sl" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px"></div><div id="cm" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.3);z-index:100;align-items:center;justify-content:center"></div>`;
  loadSL();
}
async function loadSL(){const r=await api('/strategies');const e=$('sl');if(!e)return;if(!r?.items?.length){e.innerHTML='<div style="text-align:center;padding:40px;color:#94a3b8">暂无策略，点击「新建」开始</div>';return}
e.innerHTML=r.items.map(s=>`<div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:18px"><div style="display:flex;justify-content:space-between;margin-bottom:10px"><div><b>${s.name}</b><div style="font-size:10px;color:#94a3b8">${s.strategy_type}</div></div><span style="padding:2px 8px;border-radius:10px;font-size:10px;font-weight:700;background:${s.status==='running'?'#ecfdf5':'#f1f5f9'};color:${s.status==='running'?'#10b981':'#94a3b8'}">${s.status}</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><div><div style="font-size:10px;color:#94a3b8">收益</div><div style="font-size:13px;font-weight:600;font-family:'JetBrains Mono',monospace;color:${(s.total_return||0)>=0?'#10b981':'#ef4444'}">${(s.total_return||0).toFixed(2)}%</div></div><div><div style="font-size:10px;color:#94a3b8">回撤</div><div style="font-size:13px;font-weight:600;font-family:'JetBrains Mono',monospace">${(s.max_drawdown||0).toFixed(2)}%</div></div><div><div style="font-size:10px;color:#94a3b8">胜率</div><div style="font-size:13px;font-weight:600;font-family:'JetBrains Mono',monospace">${(s.win_rate||0).toFixed(1)}%</div></div><div><div style="font-size:10px;color:#94a3b8">夏普</div><div style="font-size:13px;font-weight:600;font-family:'JetBrains Mono',monospace">${(s.sharpe_ratio||0).toFixed(2)}</div></div></div><div style="margin-top:12px;display:flex;gap:6px"><button onclick="tgS(${s.id},'${s.status==='running'?'paused':'running'}')" style="padding:4px 10px;border-radius:6px;font-size:11px;cursor:pointer;border:${s.status==='running'?'1px solid #e2e8f0':'none'};background:${s.status==='running'?'transparent':'#10b981'};color:${s.status==='running'?'#475569':'#fff'}">${s.status==='running'?'暂停':'启动'}</button><button onclick="if(confirm('确认?'))dlS(${s.id})" style="padding:4px 10px;border-radius:6px;font-size:11px;cursor:pointer;border:1px solid #e2e8f0;background:transparent;color:#475569">删除</button></div></div>`).join('')}

function showCS(){const m=$('cm');m.style.display='flex';m.innerHTML=`<div style="background:#fff;border-radius:12px;width:400px"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;display:flex;justify-content:space-between"><b>新建策略</b><button onclick="$('cm').style.display='none'" style="border:none;background:none;cursor:pointer">✕</button></div><div style="padding:18px"><div style="margin-bottom:12px"><label style="font-size:11px;font-weight:600;color:#475569">名称</label><input id="cn" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px"></div><div style="margin-bottom:12px"><label style="font-size:11px;font-weight:600;color:#475569">类型</label><select id="ct" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px">${ST.map(t=>`<option value="${t.key}">${t.name}</option>`).join('')}</select></div><div style="margin-bottom:12px"><label style="font-size:11px;font-weight:600;color:#475569">股票池</label><input id="cp" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;font-family:'JetBrains Mono',monospace;margin-top:4px" placeholder="000001.SZ,600519.SH"></div><div style="display:flex;gap:8px"><button onclick="crtS()" style="flex:1;padding:8px;border-radius:6px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:#10b981;color:#fff">创建</button><button onclick="$('cm').style.display='none'" style="flex:1;padding:8px;border-radius:6px;font-size:12px;cursor:pointer;border:1px solid #e2e8f0;background:transparent;color:#475569">取消</button></div></div></div>`}
async function crtS(){const n=$('cn').value,t=$('ct').value,p=$('cp').value.split(',').map(s=>s.trim()).filter(Boolean);if(!n){toast('请填写名称','error');return}const r=await api('/strategies',{method:'POST',body:JSON.stringify({name:n,strategy_type:t,stock_pool:p})});if(r){toast('创建成功');$('cm').style.display='none';loadSL()}}
async function tgS(id,s){await api('/strategies/'+id+'/status',{method:'PUT',body:JSON.stringify({status:s})});loadSL()}
async function dlS(id){await api('/strategies/'+id,{method:'DELETE'});loadSL()}

// ---- BACKTEST ----
function r_backtest(){
  const td=new Date().toISOString().split('T')[0];
  $('bc').innerHTML=`<div style="display:flex;margin-bottom:16px;border-bottom:1px solid #e2e8f0"><div id="tf" onclick="btT('f')" style="padding:8px 14px;font-size:12px;font-weight:600;color:#10b981;border-bottom:2px solid #10b981;cursor:pointer">新建回测</div><div id="th" onclick="btT('h')" style="padding:8px 14px;font-size:12px;color:#94a3b8;cursor:pointer;border-bottom:2px solid transparent">历史回测</div></div>
  <div id="btf"><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">🔬 策略回测</div><div style="padding:18px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><div><label style="font-size:11px;font-weight:600;color:#475569">策略</label><select id="btp" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px">${ST.map(t=>`<option value="${t.key}">${t.name}</option>`).join('')}</select></div><div><label style="font-size:11px;font-weight:600;color:#475569">股票</label><input id="btc" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;font-family:'JetBrains Mono',monospace;margin-top:4px" placeholder="000001.SZ"></div><div><label style="font-size:11px;font-weight:600;color:#475569">开始</label><input id="bts" type="date" value="2024-01-01" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px"></div><div><label style="font-size:11px;font-weight:600;color:#475569">结束</label><input id="bte" type="date" value="${td}" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px"></div><div><label style="font-size:11px;font-weight:600;color:#475569">资金</label><input id="bt$" type="number" value="1000000" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px"></div><div><label style="font-size:11px;font-weight:600;color:#475569">佣金</label><input id="btcm" type="number" step="0.0001" value="0.0003" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px"></div></div><button onclick="runBT()" style="margin-top:14px;padding:8px 24px;border-radius:6px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:#10b981;color:#fff">▶ 开始回测</button></div></div><div id="btr"></div></div>
  <div id="bth" style="display:none"><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead style="background:#f1f5f9"><tr>${['时间','股票','总收益','年化','回撤','夏普','胜率','交易'].map(h=>`<th style="padding:9px 12px;text-align:left;font-size:10px;font-weight:600;color:#475569">${h}</th>`).join('')}</tr></thead><tbody id="bhtb"></tbody></table></div></div></div>`;
  loadBH();
}
function btT(t){$('btf').style.display=t==='f'?'block':'none';$('bth').style.display=t==='h'?'block':'none';$('tf').style.cssText=`padding:8px 14px;font-size:12px;cursor:pointer;border-bottom:2px solid ${t==='f'?'#10b981':'transparent'};color:${t==='f'?'#10b981':'#94a3b8'};font-weight:${t==='f'?'600':'500'}`;$('th').style.cssText=`padding:8px 14px;font-size:12px;cursor:pointer;border-bottom:2px solid ${t==='h'?'#10b981':'transparent'};color:${t==='h'?'#10b981':'#94a3b8'};font-weight:${t==='h'?'600':'500'}`}

async function runBT(){
  const tp=$('btp').value,co=$('btc').value,sd=$('bts').value.replace(/-/g,''),ed=$('bte').value.replace(/-/g,''),ca=+$('bt$').value,cm=+$('btcm').value;
  if(!tp||!co){toast('请填写','error');return}toast('回测中...');
  const r=await api('/backtest/run',{method:'POST',body:JSON.stringify({strategy_type:tp,ts_code:co,start_date:sd,end_date:ed,initial_cash:ca,commission:cm})});
  if(r&&!r.error){
    $('btr').innerHTML=`<div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;margin-top:16px"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">📊 结果</div><div style="padding:18px"><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px">${[['总收益率',r.total_return],['年化收益',r.annual_return],['最大回撤',r.max_drawdown],['夏普比率',r.sharpe_ratio],['胜率',r.win_rate],['盈亏比',r.profit_loss_ratio],['交易次数',r.total_trades],['最终资产',r.final_value]].map(([l,v])=>`<div style="background:#f1f5f9;padding:12px;border-radius:6px;text-align:center"><div style="font-size:10px;color:#94a3b8">${l}</div><div style="font-size:16px;font-weight:700;font-family:'JetBrains Mono',monospace">${typeof v==='number'?v.toFixed(2):v}</div></div>`).join('')}</div><canvas id="btCh" height="180" style="margin-top:14px"></canvas></div></div>
    <div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;margin-top:14px"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">📋 交易 (${(r.trades||[]).length})</div><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead style="background:#f1f5f9"><tr>${['日期','方向','价格','数量','盈亏','信号'].map(h=>`<th style="padding:9px 12px;text-align:left;font-size:10px;font-weight:600;color:#475569">${h}</th>`).join('')}</tr></thead><tbody>${(r.trades||[]).map(t=>`<tr style="border-bottom:1px solid #f1f5f9"><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${t.date}</td><td style="padding:8px 12px;color:${t.direction==='buy'?'#10b981':'#ef4444'};font-weight:600">${t.direction==='buy'?'买':'卖'}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${t.price?.toFixed(2)}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${t.volume}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px;color:${(t.profit||0)>=0?'#10b981':'#ef4444'}">${t.profit?'¥'+t.profit.toFixed(0):'-'}</td><td style="padding:8px 12px">${t.signal||'-'}</td></tr>`).join('')}</tbody></table></div></div>`;
    setTimeout(()=>{const ctx=$('btCh');if(ctx&&r.equity_curve)new Chart(ctx,{type:'line',data:{labels:r.equity_curve.map((_,i)=>i),datasets:[{data:r.equity_curve,borderColor:'#10b981',backgroundColor:'rgba(16,185,129,.1)',fill:true,tension:.3,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{display:false},y:{ticks:{callback:v=>'¥'+(v/10000).toFixed(0)+'万'}}}}})},100);
    toast('回测完成！');loadBH();
  }else toast(r?.error||'失败','error');
}
async function loadBH(){const r=await api('/backtest/results');const e=$('bhtb');if(!e)return;if(!r?.items?.length){e.innerHTML='<tr><td colspan="8" style="padding:30px;text-align:center;color:#94a3b8">暂无记录</td></tr>';return}e.innerHTML=r.items.map(h=>`<tr style="border-bottom:1px solid #f1f5f9">${[(h.created_at||'').substr(0,16),h.start_date+'~'+h.end_date,h.total_return?.toFixed(2)+'%',h.annual_return?.toFixed(2)+'%',h.max_drawdown?.toFixed(2)+'%',h.sharpe_ratio?.toFixed(3),h.win_rate?.toFixed(1)+'%',h.total_trades].map(v=>`<td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${v}</td>`).join('')}</tr>`).join('')}

// ---- MARKET ----
function r_market(){$('bc').innerHTML=`<div style="display:flex;gap:10px;margin-bottom:14px"><input id="mkC" style="flex:1;max-width:400px;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;font-family:'JetBrains Mono',monospace" value="000001.SZ,600519.SH,000858.SZ"><button onclick="loadMk()" style="padding:7px 14px;border-radius:6px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:#10b981;color:#fff">查询</button></div><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead style="background:#f1f5f9"><tr>${['代码','名称','最新价','涨跌幅','成交量','成交额','最高','最低','今开'].map(h=>`<th style="padding:9px 12px;text-align:left;font-size:10px;font-weight:600;color:#475569">${h}</th>`).join('')}</tr></thead><tbody id="mktb"><tr><td colspan="9" style="padding:30px;text-align:center;color:#94a3b8">点击「查询」获取数据</td></tr></tbody></table></div></div>`}
async function loadMk(){const r=await api('/data/realtime?codes='+encodeURIComponent($('mkC').value));const e=$('mktb');if(!e)return;if(!r?.items?.length){e.innerHTML='<tr><td colspan="9" style="padding:30px;text-align:center;color:#94a3b8">无数据（需启动后端）</td></tr>';return}e.innerHTML=r.items.map(s=>`<tr style="border-bottom:1px solid #f1f5f9"><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${s.ts_code}</td><td style="padding:8px 12px">${s.name}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px;font-weight:600">${s.price}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px;font-weight:600;color:${s.change_pct>=0?'#ef4444':'#10b981'}">${s.change_pct>=0?'+':''}${s.change_pct?.toFixed(2)}%</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${(s.vol/10000).toFixed(0)}万</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${(s.amount/10000).toFixed(0)}万</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${s.high}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${s.low}</td><td style="padding:8px 12px;font-family:'JetBrains Mono',monospace;font-size:11px">${s.open}</td></tr>`).join('')}

// ---- RISK ----
function r_risk(){$('bc').innerHTML=`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px">${[['未处理','0'],['严重','0','#ef4444'],['警告','0','#f59e0b']].map(([l,v,c])=>`<div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:16px 18px"><div style="font-size:11px;color:#94a3b8;margin-bottom:4px">${l}</div><div style="font-size:22px;font-weight:700;font-family:'JetBrains Mono',monospace${c?';color:'+c:''}">${v}</div></div>`).join('')}</div><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">🔔 告警</div><div id="alL" style="padding:12px;font-size:12px;color:#94a3b8">加载中...</div></div>`;(async()=>{const r=await api('/risk/alerts');const e=$('alL');if(e){if(r?.items?.length)e.innerHTML=r.items.map(a=>`<div style="padding:8px 0;border-bottom:1px solid #f1f5f9"><b>${a.title}</b><div style="font-size:11px;color:#94a3b8">${a.detail||''}</div></div>`).join('');else e.textContent='暂无告警'}})()}

// ---- SETTINGS ----
function r_settings(){$('bc').innerHTML=`<div style="max-width:500px"><div style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="padding:14px 18px;border-bottom:1px solid #f1f5f9;font-size:13px;font-weight:700">📡 API 配置</div><div style="padding:18px"><div style="margin-bottom:12px"><label style="font-size:11px;font-weight:600;color:#475569">后端地址</label><input id="sApi" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;font-family:'JetBrains Mono',monospace;margin-top:4px" value="${API}"></div><div style="margin-bottom:12px"><label style="font-size:11px;font-weight:600;color:#475569">Tushare Token</label><input id="sTs" style="width:100%;padding:7px 10px;border:1px solid #e2e8f0;border-radius:6px;font-size:12px;margin-top:4px" placeholder="可选"></div><button onclick="localStorage.setItem('qw_api',$('sApi').value);toast('已保存')" style="padding:7px 14px;border-radius:6px;font-size:12px;font-weight:600;cursor:pointer;border:none;background:#10b981;color:#fff">保存</button></div></div></div>`}
